### ISSUE TITLE
Consider replacing yarn with npm

### ISSUE THREAD

**Issue by nbaksalyar** [pax-lang/pax#33]
`yarn` is an extra dependency which requires a user to take more prerequisite actions before starting to use pax-cli.

Considering that nowadays `npm` is largely equivalent to `yarn`, it might be beneficial to also support it as a build tool because it's already packaged together with NodeJS.

Alternatively, a Rust-based bundler such as [swc](https://github.com/swc-project/swc) can be considered. This would remove the dependency on NodeJS altogether.

**Comment by zackbrown** [comment]
I support this and will see how much of it I can work it into my current new-user-experience work at `zb/dep-rethink`.  

Dropping `yarn` should be easy — a port to `swc` would require more effort, but it would be really nice to remove the recurring pains of webpack from our lives.  Off the top of my head, to remove webpack we'd need to use swc (and some scripting, I presume) to:

 - bundle assets like images
 - compile typescript and minify/bundle output (maybe `tsc` does this by itself nowadays?)
 - load wasm, produced by the Pax compiler by way of wasm-pack
 - generate / splice all dynamic assets into the template `index.html` in the web chassis

Regarding removing NodeJS altogether, would we still need `npm` or some other Node-based package manager for dependency installation / management?  It didn't look like `swc` handles this but are you aware of some production-ready, non-Node-based, npm-compatible package manager?  

Removing Node entirely as a dependency sounds like a major upgrade to the new-developer-onboarding experience.

**Comment by zackbrown** [comment]
Removed `yarn` dependency in favor of `npm` for Web builds in #44

We'll come back for removing a Node dependency entirely (e.g. via `swc` or `bun`), as that would be a great friction reducer.  Closing this issue as nominally resolved.
